import Head from 'next/head'
import { Inter } from 'next/font/google'
import { DefaultLayout } from '@/components/Layout/DefaultLayout'
import { Header } from '@/components/TopPage/Header'
import { Visual } from '@/components/TopPage/Visual'
import { Profile } from '@/components/TopPage/Profile'
import { Skills } from '@/components/TopPage/Skills'
import { Blog } from '@/components/TopPage/Blog'
import { Works } from '@/components/TopPage/Works'
import { Contact } from '@/components/TopPage/Contact'
import { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Header />
        <Visual />
        <main style={{ padding: '0 10%' }}>
          <Profile />
          <Skills />
          <Blog />
          <Works />
          <Contact />
        </main>
        <footer
          style={{
            width: '100%',
            background: '#3E39A2',
            height: 40,

            bottom: 0,
          }}
        />
      </DefaultLayout>
    </>
  )
}
export default Home
