import Head from 'next/head'

import { DefaultLayout } from '@/components/Layout/DefaultLayout'
import { Header } from '@/components/TopPage/Header'
import { Visual } from '@/components/TopPage/Visual'
import { Profile } from '@/components/TopPage/Profile'
import { Skills } from '@/components/TopPage/Skills'
//import { Blog } from '@/components/TopPage/Blog'
//import { Works } from '@/components/TopPage/Works'
import { Contact } from '@/components/TopPage/Contact'
import { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>OCHA.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta property="og:title" content="OCHA.dev" />
        <meta property="og:url" content={'お茶.dev'} />
        <meta property="og:title" content={'OCHA.dev'} />
        <meta property="og:site_name" content={'お茶のポートフォリオ'} />
        <meta property="og:description" content={'どうも、お茶です'} />
        <meta property="og:type" content="website" />
        <meta
          property="og:image"
          content={'https://xn--t8jy01w.dev//images/ogp.png'}
        />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@makura_nageru" />
        <meta name="twitter:title" content="お茶.dev" />
        <meta name="twitter:description" content="どうも、お茶です" />
        <meta
          name="twitter:image"
          content="https://xn--t8jy01w.dev/images/ogp.png"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Header />
        <Visual />
        <main style={{ padding: '0 10%', display: 'grid', gap: 20 }}>
          <Profile />
          <Skills />
          {/*
          TODO:そのうち作る
          <Blog />
          <Works />*/}
          <Contact />
        </main>
        <footer
          style={{
            width: '100%',

            height: 40,
            bottom: 0,
          }}
        />
      </DefaultLayout>
    </>
  )
}
export default Home
