import { DefaultLayout } from '@/components/Layout/DefaultLayout'
import { Career } from '@/components/ProfilePage/Career'
import { Profile } from '@/components/ProfilePage/Profile'
import { ProfileDiscription } from '@/components/ProfilePage/ProfileDescription'
import { Header } from '@/components/TopPage/Header'
import { NextPage } from 'next'
import { Text } from '@chakra-ui/react'
import Head from 'next/head'

const ProfilePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>OCHA.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta property="og:title" content="OCHA.dev" />
        <meta property="og:url" content={'お茶.dev'} />
        <meta property="og:title" content={'OCHA.dev'} />
        <meta property="og:site_name" content={'お茶のポートフォリオ'} />
        <meta property="og:description" content={'どうも、お茶です'} />
        <meta property="og:type" content="website" />
        <meta property="og:image" content={'https://お茶.dev/images/ogp.png'} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@makura_nageru" />
        <meta name="twitter:title" content="お茶.dev" />
        <meta name="twitter:description" content="どうも、お茶です" />
        <meta name="twitter:image" content="https://お茶.dev/images/ogp.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Header />
        <main style={{ padding: '0 10%', display: 'grid', gap: 20 }}>
          <Profile />
          <ProfileDiscription>
            <Text>
              高専から編入して琵琶湖の限界大学生になりました。
              <br />
              メンヘラテクノロジーでエンジニアとしてお世話になっています。
              <br />
              朝と直射日光と膝関節が弱点です。
            </Text>
          </ProfileDiscription>
          <Career />
        </main>
      </DefaultLayout>
    </>
  )
}

export default ProfilePage
