import Head from 'next/head'

type Props = {
  title: string
  ogpImage: string
  description: string
  path?: string
}

export const DeafaultHead = ({ title, ogpImage, description, path }: Props) => {
  return (
    <Head>
      <title>OCHA.dev</title>
      <meta name="description" content="Generated by create next app" />
      <meta charSet="utf-8" />
      <meta
        property="og:url"
        content={
          path
            ? `https://www.xn--t8jy01w.dev/${path}`
            : 'https://www.xn--t8jy01w.dev/'
        }
      />
      <meta
        name="google-site-verification"
        content="f5ovWE1TWUnqmRqOyAVOxAIwugeDmIRusp6vLjlGUNg"
      />
      <meta property="og:title" content={title} />
      <meta property="og:site_name" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:type" content="website" />
      <meta property="og:image" content={ogpImage} />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="@makura_nageru" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={ogpImage} />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
